### PR TITLE
Allow email list as possible recipient

### PR DESCRIPTION
**Pull request by Jorilx**
This PR allows to specify more than one email address as possible recipient, so if you need to setup autoreply for a large number of addresses you don't have to create a huge autoreply.json

### CODE REVIEW

**Comment by innovara** [comment]
Thanks. Can you drop commit 'Don't alter whitespace' f86c6c617de3e86557b1dded20e4e544783d969b? I'd like to fix that too. It'd be even better if the feature adding the list of emails goes in one commit and the fixing of the white spaces goes on another one, if that is not too much bother.

**Comment by Jorilx** [comment]
Ok will do!

**Comment by Jorilx** [comment]
...oops I see you've already merged it, guess it's ok then :) Thanks!

**Comment by innovara** [comment]
Yes, sorry, I am not too familiar with the merge process and I found a way of doing what I wanted while keeping your contribution so I didn't want to bother you. Thanks for your contribution

**Pull request closed without merging**
